-- ไม่จำเป็นต้องรันเอง: เซิร์ฟเวอร์สร้างให้อัตโนมัติตอนเปิด (ปลอดภัยถ้ารันซ้ำ)
-- ใส่ไว้เผื่ออยากรันใน Supabase SQL Editor ล่วงหน้า

-- สมาชิกเดิมทุกคนได้ค่า TRUE อัตโนมัติ จึงไม่ถูกล็อก
ALTER TABLE customer ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS email_token (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
  type VARCHAR(10) NOT NULL CHECK (type IN ('verify','reset')),
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_email_token_customer ON email_token (customer_id, type);
