-- SunFlowerPC / Online PC Rental System
-- Supabase PostgreSQL schema
-- Run this file in Supabase SQL Editor after selecting the project's postgres database.

DROP TABLE IF EXISTS email_token CASCADE;
DROP TABLE IF EXISTS rating CASCADE;
DROP TABLE IF EXISTS support_ticket_message CASCADE;
DROP TABLE IF EXISTS support_ticket CASCADE;
DROP TABLE IF EXISTS topup_payment CASCADE;
DROP TABLE IF EXISTS wallet_transaction CASCADE;
DROP TABLE IF EXISTS session_extension CASCADE;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS rental CASCADE;
DROP TABLE IF EXISTS reservation CASCADE;
DROP TABLE IF EXISTS computer CASCADE;
DROP TABLE IF EXISTS wallet CASCADE;
DROP TABLE IF EXISTS customer CASCADE;

DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

CREATE TABLE customer (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  phone VARCHAR(30),
  email_verified BOOLEAN NOT NULL DEFAULT TRUE,
  role VARCHAR(20) NOT NULL DEFAULT 'customer'
    CHECK (role IN ('customer', 'admin')),
  time_balance_minutes INTEGER NOT NULL DEFAULT 0
    CHECK (time_balance_minutes >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wallet (
  wallet_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL UNIQUE,
  balance NUMERIC(10,2) NOT NULL DEFAULT 0.00
    CHECK (balance >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_wallet_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);

CREATE TABLE computer (
  computer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  computer_code VARCHAR(20) NOT NULL UNIQUE,
  cpu VARCHAR(120) NOT NULL,
  ram VARCHAR(80) NOT NULL,
  gpu VARCHAR(120) NOT NULL,
  storage VARCHAR(80) NOT NULL,
  price_per_hour NUMERIC(10,2) NOT NULL
    CHECK (price_per_hour >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'available'
    CHECK (status IN ('available', 'reserved', 'in_use', 'maintenance')),
  connection_address VARCHAR(120) NOT NULL DEFAULT '10.0.8.10',
  connection_port INTEGER NOT NULL DEFAULT 3389
    CHECK (connection_port BETWEEN 1 AND 65535),
  connection_method VARCHAR(40) NOT NULL DEFAULT 'RDP',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reservation (
  reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  computer_id INTEGER NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  hours NUMERIC(10,2) NOT NULL CHECK (hours > 0),
  total_price NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'confirmed'
    CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reservation_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_reservation_computer
    FOREIGN KEY (computer_id) REFERENCES computer(computer_id)
);

CREATE TABLE rental (
  rental_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  computer_id INTEGER NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  hours NUMERIC(10,2) NOT NULL CHECK (hours > 0),
  price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'reserved', 'completed', 'cancelled', 'saved')),
  remaining_minutes INTEGER NOT NULL DEFAULT 0
    CHECK (remaining_minutes >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rental_reservation
    FOREIGN KEY (reservation_id) REFERENCES reservation(reservation_id),
  CONSTRAINT fk_rental_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_rental_computer
    FOREIGN KEY (computer_id) REFERENCES computer(computer_id)
);

CREATE TABLE session (
  session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_id INTEGER NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  remaining_seconds INTEGER NOT NULL DEFAULT 0
    CHECK (remaining_seconds >= 0),
  status VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'ended', 'saved')),
  connection_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  access_key VARCHAR(20) UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_session_rental
    FOREIGN KEY (rental_id) REFERENCES rental(rental_id)
);

CREATE TABLE session_extension (
  extension_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL
    CHECK (type IN ('save_time', 'extend')),
  minutes INTEGER NOT NULL CHECK (minutes > 0),
  note VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_extension_session
    FOREIGN KEY (session_id) REFERENCES session(session_id)
);

CREATE TABLE wallet_transaction (
  transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL
    CHECK (type IN ('topup', 'rental', 'refund')),
  amount NUMERIC(10,2) NOT NULL,
  description VARCHAR(255) NOT NULL,
  method VARCHAR(40) NOT NULL DEFAULT 'wallet',
  status VARCHAR(20) NOT NULL DEFAULT 'success'
    CHECK (status IN ('success', 'pending', 'failed')),
  rental_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transaction_wallet
    FOREIGN KEY (wallet_id) REFERENCES wallet(wallet_id),
  CONSTRAINT fk_transaction_rental
    FOREIGN KEY (rental_id) REFERENCES rental(rental_id)
);

CREATE TABLE topup_payment (
  topup_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  reference_code VARCHAR(40) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'submitted', 'approved', 'rejected', 'paid', 'expired', 'cancelled')),
  qr_type VARCHAR(20) NOT NULL DEFAULT 'static'
    CHECK (qr_type = 'static'),
  slip_path VARCHAR(255),
  slip_submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by INTEGER,
  review_note VARCHAR(255),
  expires_at TIMESTAMPTZ NOT NULL,
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_topup_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_topup_reviewer
    FOREIGN KEY (reviewed_by) REFERENCES customer(customer_id)
);

CREATE TABLE support_ticket (
  ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL,
  computer_id INTEGER,
  subject VARCHAR(160) NOT NULL,
  description TEXT NOT NULL,
  issue_type VARCHAR(80) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  admin_reply TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ticket_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_ticket_computer
    FOREIGN KEY (computer_id) REFERENCES computer(computer_id)
);

CREATE TABLE support_ticket_message (
  message_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id INTEGER NOT NULL,
  sender_customer_id INTEGER NOT NULL,
  sender_role VARCHAR(20) NOT NULL
    CHECK (sender_role IN ('customer', 'admin')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ticket_message_ticket
    FOREIGN KEY (ticket_id) REFERENCES support_ticket(ticket_id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_message_sender
    FOREIGN KEY (sender_customer_id) REFERENCES customer(customer_id)
);

CREATE INDEX idx_ticket_message_ticket
  ON support_ticket_message(ticket_id);

CREATE TABLE rating (
  rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_id INTEGER NOT NULL,
  customer_id INTEGER NOT NULL,
  computer_id INTEGER NOT NULL,
  score SMALLINT NOT NULL CHECK (score BETWEEN 1 AND 5),
  comment VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rating_rental
    FOREIGN KEY (rental_id) REFERENCES rental(rental_id),
  CONSTRAINT fk_rating_customer
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_rating_computer
    FOREIGN KEY (computer_id) REFERENCES computer(computer_id)
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_customer_updated_at
BEFORE UPDATE ON customer
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_wallet_updated_at
BEFORE UPDATE ON wallet
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_computer_updated_at
BEFORE UPDATE ON computer
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_ticket_updated_at
BEFORE UPDATE ON support_ticket
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE email_token (
  token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
  type VARCHAR(10) NOT NULL CHECK (type IN ('verify','reset')),
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_email_token_customer ON email_token (customer_id, type);
