const crypto = require('crypto');
const pool = require('../config/db');

const hash = (raw) => crypto.createHash('sha256').update(raw).digest('hex');

// สร้างตาราง/คอลัมน์ที่ต้องใช้ตอนเปิดเซิร์ฟเวอร์ (ปลอดภัยถ้ารันซ้ำ)
// สมาชิกเดิมจะได้ email_verified = TRUE อัตโนมัติ เพราะ DEFAULT TRUE
async function ensureTable() {
  await pool.query('ALTER TABLE customer ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT TRUE');
  await pool.query(`CREATE TABLE IF NOT EXISTS email_token (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
    type VARCHAR(10) NOT NULL CHECK (type IN ('verify','reset')),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await pool.query('CREATE INDEX IF NOT EXISTS idx_email_token_customer ON email_token (customer_id, type)');
}

// คืนค่า token ดิบ (ส่งทางอีเมล) — ในฐานข้อมูลเก็บเฉพาะค่าแฮช
async function create(customerId, type, minutes) {
  const raw = crypto.randomBytes(32).toString('hex');
  await pool.query(
    `INSERT INTO email_token (customer_id, type, token_hash, expires_at)
     VALUES (?, ?, ?, CURRENT_TIMESTAMP + (? * INTERVAL '1 minute'))`,
    [customerId, type, hash(raw), minutes]
  );
  return raw;
}

// ใช้โทเคนได้ครั้งเดียว: คืน customer_id ถ้าถูกต้อง/ยังไม่หมดอายุ/ยังไม่เคยใช้ ไม่งั้น null
async function consume(raw, type) {
  if (!raw || typeof raw !== 'string') return null;
  const [r] = await pool.query(
    `UPDATE email_token SET used_at = CURRENT_TIMESTAMP
     WHERE token_hash = ? AND type = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
     RETURNING customer_id`,
    [hash(raw), type]
  );
  return r.rows && r.rows[0] ? r.rows[0].customer_id : null;
}

// true ถ้าเพิ่งขอไปไม่ถึง 60 วินาที (กันกดขอรัวๆ จนถูกใช้ส่งสแปม)
async function recentlyIssued(customerId, type, seconds = 60) {
  const [rows] = await pool.query(
    `SELECT 1 FROM email_token WHERE customer_id = ? AND type = ?
     AND created_at > CURRENT_TIMESTAMP - (? * INTERVAL '1 second') LIMIT 1`,
    [customerId, type, seconds]
  );
  return rows.length > 0;
}

async function invalidateAll(customerId, type) {
  await pool.query(
    'UPDATE email_token SET used_at = CURRENT_TIMESTAMP WHERE customer_id = ? AND type = ? AND used_at IS NULL',
    [customerId, type]
  );
}

async function purgeOld() {
  await pool.query("DELETE FROM email_token WHERE expires_at < CURRENT_TIMESTAMP - INTERVAL '7 days'");
}

module.exports = { ensureTable, create, consume, recentlyIssued, invalidateAll, purgeOld };
