const pool = require('../config/db');

async function ensureTable() {
  await pool.query(`CREATE TABLE IF NOT EXISTS topup_payment (
    topup_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    reference_code VARCHAR(40) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','submitted','approved','rejected','paid','expired','cancelled')),
    qr_type VARCHAR(20) NOT NULL DEFAULT 'static' CHECK (qr_type = 'static'),
    expires_at TIMESTAMPTZ NOT NULL,
    paid_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_topup_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
  )`);
  try { await pool.query("ALTER TABLE topup_payment ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ NULL"); } catch (_) {}
}

async function expireOld() {
  await pool.query(`UPDATE topup_payment SET status='expired' WHERE status='pending' AND expires_at <= CURRENT_TIMESTAMP`);
}

async function create(customerId, amount, referenceCode, expiresAt) {
  const [r] = await pool.query(
    `INSERT INTO topup_payment (customer_id,amount,reference_code,expires_at) VALUES (?,?,?,?) RETURNING topup_id`,
    [customerId, amount, referenceCode, expiresAt]
  );
  return findById(r.insertId, customerId);
}

async function findById(id, customerId=null) {
  const [rows] = await pool.query(
    `SELECT tp.*,c.full_name,c.email FROM topup_payment tp JOIN customer c ON c.customer_id=tp.customer_id WHERE tp.topup_id=? ${customerId ? 'AND tp.customer_id=?':''}`,
    customerId ? [id,customerId] : [id]
  );
  return rows[0] || null;
}

async function listByCustomer(customerId) {
  await expireOld();
  const [rows]=await pool.query('SELECT * FROM topup_payment WHERE customer_id=? ORDER BY created_at DESC LIMIT 30',[customerId]);
  return rows;
}

async function markPaidByReference(referenceCode, amount) {
  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();
    const [rows] = await conn.query('SELECT * FROM topup_payment WHERE reference_code=? FOR UPDATE',[referenceCode]);
    const p = rows[0];
    if (!p) throw Object.assign(new Error('ไม่พบรายการเติมเงิน'), { status: 404 });
    if (p.status === 'paid') { await conn.commit(); return p; }
    if (p.status !== 'pending') throw Object.assign(new Error('รายการเติมเงินหมดอายุหรือไม่สามารถรับชำระได้'), { status: 400 });
    if (new Date(p.expires_at).getTime() <= Date.now()) {
      await conn.query("UPDATE topup_payment SET status='expired' WHERE topup_id=?",[p.topup_id]);
      await conn.commit();
      throw Object.assign(new Error('รายการเติมเงินหมดอายุแล้ว'), { status: 400 });
    }
    if (Math.abs(Number(amount) - Number(p.amount)) > 0.001) throw Object.assign(new Error('ยอดโอนไม่ตรงกับยอดรายการ'), { status: 400 });

    const [ws] = await conn.query('SELECT * FROM wallet WHERE customer_id=? FOR UPDATE',[p.customer_id]);
    const w = ws[0];
    if (!w) throw Object.assign(new Error('ไม่พบ Wallet ของลูกค้า'), { status: 400 });
    await conn.query('UPDATE wallet SET balance=balance+? WHERE wallet_id=?',[p.amount,w.wallet_id]);
    await conn.query(`INSERT INTO wallet_transaction (wallet_id,type,amount,description,method,status) VALUES (?,'topup',? ,?,'promptpay','success')`,[
      w.wallet_id,p.amount,`เติมเงินผ่าน QR #${p.reference_code}`
    ]);
    await conn.query("UPDATE topup_payment SET status='paid',paid_at=CURRENT_TIMESTAMP WHERE topup_id=?",[p.topup_id]);
    await conn.commit();
    return findById(p.topup_id);
  } catch (e) {
    try { await conn.rollback(); } catch (_) {}
    throw e;
  } finally { conn.release(); }
}


async function cancel(id, customerId) {
  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();
    const [rows] = await conn.query('SELECT * FROM topup_payment WHERE topup_id=? AND customer_id=? FOR UPDATE',[id,customerId]);
    const payment = rows[0];
    if (!payment) throw Object.assign(new Error('ไม่พบรายการเติมเงิน'), { status: 404 });
    if (payment.status !== 'pending') throw Object.assign(new Error('ไม่สามารถยกเลิกรายการนี้ได้'), { status: 400 });
    await conn.query("UPDATE topup_payment SET status='cancelled' WHERE topup_id=?",[id]);
    const [wallets] = await conn.query('SELECT wallet_id FROM wallet WHERE customer_id=? FOR UPDATE',[customerId]);
    if (wallets[0]) {
      await conn.query(`INSERT INTO wallet_transaction (wallet_id,type,amount,description,method,status) VALUES (?,'topup',?,?,'promptpay','failed')`,[
        wallets[0].wallet_id, Number(payment.amount), `เติมเงินผ่าน QR #${payment.reference_code}`
      ]);
    }
    await conn.commit();
    return findById(id, customerId);
  } catch (e) {
    try { await conn.rollback(); } catch (_) {}
    throw e;
  } finally { conn.release(); }
}

async function confirm(id, customerId) {
  await expireOld();
  const payment = await findById(id, customerId);
  if (!payment) throw Object.assign(new Error('ไม่พบรายการเติมเงิน'), { status: 404 });
  if (payment.status !== 'pending') {
    return { payment, success: payment.status === 'paid' };
  }
  if (new Date(payment.expires_at).getTime() <= Date.now()) {
    await pool.query("UPDATE topup_payment SET status='expired' WHERE topup_id=?",[id]);
    return { payment: await findById(id, customerId), success: false };
  }

  // ยังไม่มีการเชื่อมธนาคารจริง จึงใช้ค่า DEMO_PAYMENT_VERIFY_RESULT สำหรับจำลองผลตรวจสอบ
  const demoResult = String(process.env.DEMO_PAYMENT_VERIFY_RESULT || 'fail').toLowerCase();
  if (demoResult !== 'success') {
    const conn = await pool.getConnection();
    try {
      await conn.beginTransaction();
      await conn.query("UPDATE topup_payment SET status='rejected' WHERE topup_id=? AND status='pending'",[id]);
      const [wallets] = await conn.query('SELECT wallet_id FROM wallet WHERE customer_id=? FOR UPDATE',[customerId]);
      if (wallets[0]) {
        await conn.query(`INSERT INTO wallet_transaction (wallet_id,type,amount,description,method,status) VALUES (?,'topup',?,?,'promptpay','failed')`,[
          wallets[0].wallet_id, Number(payment.amount), `เติมเงินผ่าน QR #${payment.reference_code}`
        ]);
      }
      await conn.commit();
    } catch (e) {
      try { await conn.rollback(); } catch (_) {}
      throw e;
    } finally { conn.release(); }
    return { payment: await findById(id, customerId), success: false };
  }

  const paid = await markPaidByReference(payment.reference_code, Number(payment.amount));
  return { payment: paid, success: true };
}

module.exports={ensureTable,expireOld,create,findById,listByCustomer,markPaidByReference,cancel,confirm};
